<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Data Analysis with R - 13&nbsp; Grouping and summarizing data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./untangled_ls06_group_by_other_verbs.html" rel="next">
<link href="./untangled_ls04_conditional_mutate.html" rel="prev">
<link href="./logo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./untangled_ls01_select_rename.html">Data Manipulation</a></li><li class="breadcrumb-item"><a href="./untangled_ls05_groupby_summarize.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Grouping and summarizing data</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Analysis with R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/the-graph-courses/idar_book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations_ls01_setting_up.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Setting up R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations_ls02_using_rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Using RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations_ls03_coding_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Coding basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations_ls04_data_dive_ebola_sierra_leone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data dive: Ebola in Sierra Leone</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations_ls05_projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">RStudio projects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations_ls06_rmarkdown.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">R Markdown</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations_ls07_data_structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data structures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations_ls08_01_using_chatgpt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Using ChatGPT for Data Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Data Manipulation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./untangled_ls01_select_rename.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Selecting and renaming columns</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./untangled_ls02_filter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Filtering rows</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./untangled_ls03_mutate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Mutating columns</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./untangled_ls04_conditional_mutate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Conditional mutating</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./untangled_ls05_groupby_summarize.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Grouping and summarizing data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./untangled_ls06_group_by_other_verbs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Grouped filter, mutate and arrange</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./untangled_ls07_pivoting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Pivoting data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./untangled_ls08_advanced_pivoting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Advanced pivoting</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Data Visualization</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_on_display_ls01_gg_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Intro to ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_on_display_ls02_scatter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Scatter plots and smoothing lines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_on_display_ls03_line_graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Lines, scales, and labels</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_on_display_ls04_histograms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Histograms with {ggplot2}</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_on_display_ls05_boxplots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Boxplots with {ggplot2}</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">13.1</span> Introduction</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives"><span class="header-section-number">13.2</span> Learning objectives</a></li>
  <li><a href="#the-yaounde-covid-19-dataset" id="toc-the-yaounde-covid-19-dataset" class="nav-link" data-scroll-target="#the-yaounde-covid-19-dataset"><span class="header-section-number">13.3</span> The Yaounde COVID-19 dataset</a></li>
  <li><a href="#what-are-summary-statistics" id="toc-what-are-summary-statistics" class="nav-link" data-scroll-target="#what-are-summary-statistics"><span class="header-section-number">13.4</span> What are summary statistics?</a></li>
  <li><a href="#introducing-dplyrsummarize" id="toc-introducing-dplyrsummarize" class="nav-link" data-scroll-target="#introducing-dplyrsummarize"><span class="header-section-number">13.5</span> Introducing <code>dplyr::summarize()</code></a></li>
  <li><a href="#grouped-summaries-with-dplyrgroup_by" id="toc-grouped-summaries-with-dplyrgroup_by" class="nav-link" data-scroll-target="#grouped-summaries-with-dplyrgroup_by"><span class="header-section-number">13.6</span> Grouped summaries with <code>dplyr::group_by()</code></a></li>
  <li><a href="#grouping-by-multiple-variables-nested-grouping" id="toc-grouping-by-multiple-variables-nested-grouping" class="nav-link" data-scroll-target="#grouping-by-multiple-variables-nested-grouping"><span class="header-section-number">13.7</span> Grouping by multiple variables (nested grouping)</a></li>
  <li><a href="#ungrouping-with-dplyrungroup-why-and-how" id="toc-ungrouping-with-dplyrungroup-why-and-how" class="nav-link" data-scroll-target="#ungrouping-with-dplyrungroup-why-and-how"><span class="header-section-number">13.8</span> Ungrouping with <code>dplyr::ungroup()</code> (why and how)</a></li>
  <li><a href="#counting-rows" id="toc-counting-rows" class="nav-link" data-scroll-target="#counting-rows"><span class="header-section-number">13.9</span> Counting rows</a>
  <ul class="collapse">
  <li><a href="#counting-rows-that-meet-a-condition" id="toc-counting-rows-that-meet-a-condition" class="nav-link" data-scroll-target="#counting-rows-that-meet-a-condition"><span class="header-section-number">13.9.1</span> Counting rows that meet a condition</a></li>
  <li><a href="#dplyrcount" id="toc-dplyrcount" class="nav-link" data-scroll-target="#dplyrcount"><span class="header-section-number">13.9.2</span> dplyr::count()</a></li>
  </ul></li>
  <li><a href="#including-missing-combinations-in-summaries" id="toc-including-missing-combinations-in-summaries" class="nav-link" data-scroll-target="#including-missing-combinations-in-summaries"><span class="header-section-number">13.10</span> Including missing combinations in summaries</a></li>
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up"><span class="header-section-number">13.11</span> Wrap up</a></li>
  <li><a href="#solutions" id="toc-solutions" class="nav-link" data-scroll-target="#solutions"><span class="header-section-number">13.12</span> Solutions</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/the-graph-courses/idar_book/edit/main/untangled_ls05_groupby_summarize.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/the-graph-courses/idar_book/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Grouping and summarizing data</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">13.1</span> Introduction</h2>
<p>You currently know how to keep your data entries of interest, how keep relevant variables and how to modify them or create new ones.</p>
<p>Now, we will take your data wrangling skills one step further by understanding how to easily extract summary statistics, through the verb <code>summarize()</code>, such as calculating the mean of a variable.</p>
<p>Moreover, we will begin exploring a crucial verb, <code>group_by()</code>, capable of grouping your variables together to perform grouped operations on your data set.</p>
<p>Let’s go !</p>
<hr>
</section>
<section id="learning-objectives" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">13.2</span> Learning objectives</h2>
<ol type="1">
<li><p>You can use <code>dplyr::summarize()</code> to extract summary statistics from datasets.</p></li>
<li><p>You can use <code>dplyr::group_by()</code> to group data by one or more variables before performing operations on them.</p></li>
<li><p>You understand why and how to ungroup grouped data frames.</p></li>
<li><p>You can use <code>dplyr::n()</code> together with <code>group_by()</code>-<code>summarize()</code> to count rows per group.</p></li>
<li><p>You can use <code>sum()</code> together with <code>group_by()</code>-<code>summarize()</code> to count rows that meet a condition.</p></li>
<li><p>You can use <code>dplyr::count()</code> as a handy function to count rows per group.</p></li>
</ol>
<hr>
</section>
<section id="the-yaounde-covid-19-dataset" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="the-yaounde-covid-19-dataset"><span class="header-section-number">13.3</span> The Yaounde COVID-19 dataset</h2>
<p>In this lesson, we will again use data from the COVID-19 serological survey conducted in Yaounde, Cameroon.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>yaounde <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">'data/yaounde_data.csv'</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="do">## A smaller subset of variables</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>yao <span class="ot">&lt;-</span> yaounde <span class="sc">%&gt;%</span> <span class="fu">select</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  age, age_category_3, sex, weight_kg, height_cm,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  neighborhood, is_smoker, is_pregnant, occupation,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  treatment_combinations, symptoms, n_days_miss_work, n_bedridden_days,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  highest_education, igg_result)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>yao</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 971 × 15
     age age_category_3 sex    weight_kg height_cm neighborhood is_smoker 
   &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;     
 1    45 Adult          Female        95       169 Briqueterie  Non-smoker
 2    55 Adult          Male          96       185 Briqueterie  Ex-smoker 
 3    23 Adult          Male          74       180 Briqueterie  Smoker    
 4    20 Adult          Female        70       164 Briqueterie  Non-smoker
 5    55 Adult          Female        67       147 Briqueterie  Non-smoker
 6    17 Child          Female        65       162 Briqueterie  Non-smoker
 7    13 Child          Female        65       150 Briqueterie  Non-smoker
 8    28 Adult          Male          62       173 Briqueterie  Non-smoker
 9    30 Adult          Male          73       170 Briqueterie  Non-smoker
10    13 Child          Female        56       153 Briqueterie  Non-smoker
# ℹ 961 more rows
# ℹ 8 more variables: is_pregnant &lt;chr&gt;, occupation &lt;chr&gt;,
#   treatment_combinations &lt;chr&gt;, symptoms &lt;chr&gt;, n_days_miss_work &lt;dbl&gt;,
#   n_bedridden_days &lt;dbl&gt;, highest_education &lt;chr&gt;, igg_result &lt;chr&gt;</code></pre>
</div>
</div>
<p>See the first lesson in this chapter for more information about this dataset.</p>
</section>
<section id="what-are-summary-statistics" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="what-are-summary-statistics"><span class="header-section-number">13.4</span> What are summary statistics?</h2>
<p>A summary statistic is a single value (such as a mean or median) that describes a sequence of values (typically a column in your dataset).</p>
<p><img src="images/what_is_a_summary_statistic.png" class="img-fluid" width="363"></p>
<p>Summary statistics can describe the center, spread or range of a variable, or the counts and positions of values within that variable. Some common summary statistics are shown in the diagram below:</p>
<p><img src="images/summary_stats_examples.png" class="img-fluid" width="495"></p>
<p>Computing summary statistics is a very common operation in most data analysis workflows, so it will be important to become fluent in extracting them from your datasets. And for this task, there is no better tool than the {dplyr} function <code>summarize()</code>! So let’s see how to use this powerful function.</p>
</section>
<section id="introducing-dplyrsummarize" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="introducing-dplyrsummarize"><span class="header-section-number">13.5</span> Introducing <code>dplyr::summarize()</code></h2>
<p>To get started, it is best to first consider how to get simple summary statistics <em>without</em> using <code>summarize()</code>, then we will consider why you <em>should</em> actually use <code>summarize()</code>.</p>
<p>Imagine you were asked to find the mean age of respondents in the <code>yao</code> data frame. How might you do this in base R?</p>
<p>First, recall that the dollar sign function, <code>$</code>, allows you to extract a data frame column to a vector:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>yao<span class="sc">$</span>age <span class="co"># extract the `age` column from `yao`</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To obtain the mean, you simply pass this <code>yao$age</code> vector into the <code>mean()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(yao<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29.01751</code></pre>
</div>
</div>
<p>And that’s it! You now have a simple summary statistic. Extremely easy, right?</p>
<p>So why do we need <code>summarize()</code> to get summary statistics if the process is already so simple without it?We’ll come back to the <em>why</em> question soon. First let’s see <em>how</em> to obtain summary statistics with <code>summarize()</code>.</p>
<p>Going back to the previous example, the correct syntax to get the mean age with <code>summarize()</code> would be:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  mean_age
     &lt;dbl&gt;
1     29.0</code></pre>
</div>
</div>
<p>The anatomy of this syntax is shown below. You simply need to input name of the new column (e.g.&nbsp;<code>mean_age</code>), the summary function (e.g.&nbsp;<code>mean()</code>), and the column to summarize (e.g.&nbsp;<code>age</code>).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/summarize_syntax.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><em>Fig.</em> Basic syntax for the <code>summarize()</code> function.</figcaption>
</figure>
</div>
<hr>
<p>You can also compute multiple summary statistics in a single <code>summarize()</code> statement. For example, if you wanted both the mean and the median age, you could run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age), </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_age =</span> <span class="fu">median</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  mean_age median_age
     &lt;dbl&gt;      &lt;dbl&gt;
1     29.0         26</code></pre>
</div>
</div>
<p>Nice!</p>
<hr>
<p>Now, you should be wondering why <code>summarize()</code> puts the summary statistics into a data frame, with each statistic in a different column.</p>
<p>The main benefit of this data frame structure is to make it easy to produce <em>grouped</em> summaries (and creating such grouped summaries will be the primary benefit of using <code>summarize()</code>).</p>
<p>We will look at these grouped summaries in the next section. For now, attempt the practice questions below.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>summarize()</code> and the relevant summary functions to obtain the mean, median and standard deviation of respondent weights from the <code>weight_kg</code> variable of the <code>yao</code> data frame.</p>
<p>Your output should be a data frame with three columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>mean_weight_kg</th>
<th>median_weight_kg</th>
<th>sd_weight_kg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Q_weight_summary <span class="ot">&lt;-</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  ____________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>summarize()</code> and the relevant summary functions to obtain the minimum and maximum respondent heights from the <code>height_cm</code> variable of the <code>yao</code> data frame.</p>
<p>Your output should be a data frame with two columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>min_height_cm</th>
<th>max_height_cm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Q_height_summary <span class="ot">&lt;-</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  ____________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.CHECK_Q_height_summary</span>()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">.HINT_Q_height_summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="grouped-summaries-with-dplyrgroup_by" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="grouped-summaries-with-dplyrgroup_by"><span class="header-section-number">13.6</span> Grouped summaries with <code>dplyr::group_by()</code></h2>
<p>As its name suggests, <code>dplyr::group_by()</code> lets you group a data frame by the values in a variable (e.g.&nbsp;male vs female sex). You can then perform operations that are split according to these groups.</p>
<p>What effect does <code>group_by()</code> have on a data frame? Let’s try to group the <code>yao</code> data frame by sex and observe the effect:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 971 × 15
# Groups:   sex [2]
     age age_category_3 sex    weight_kg height_cm neighborhood is_smoker 
   &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;     
 1    45 Adult          Female        95       169 Briqueterie  Non-smoker
 2    55 Adult          Male          96       185 Briqueterie  Ex-smoker 
 3    23 Adult          Male          74       180 Briqueterie  Smoker    
 4    20 Adult          Female        70       164 Briqueterie  Non-smoker
 5    55 Adult          Female        67       147 Briqueterie  Non-smoker
 6    17 Child          Female        65       162 Briqueterie  Non-smoker
 7    13 Child          Female        65       150 Briqueterie  Non-smoker
 8    28 Adult          Male          62       173 Briqueterie  Non-smoker
 9    30 Adult          Male          73       170 Briqueterie  Non-smoker
10    13 Child          Female        56       153 Briqueterie  Non-smoker
# ℹ 961 more rows
# ℹ 8 more variables: is_pregnant &lt;chr&gt;, occupation &lt;chr&gt;,
#   treatment_combinations &lt;chr&gt;, symptoms &lt;chr&gt;, n_days_miss_work &lt;dbl&gt;,
#   n_bedridden_days &lt;dbl&gt;, highest_education &lt;chr&gt;, igg_result &lt;chr&gt;</code></pre>
</div>
</div>
<p>Hmm. Apparently nothing happened. The one thing you <em>might</em> notice is a new section in the header that tells you the grouped-by variable—sex—and the number of groups—2:</p>
<pre><code>  # A tibble: 971 × 10
👉# Groups:   sex [2]👈</code></pre>
<p>Apart from this header however, the data frame appears unchanged.</p>
<p>But watch what happens when we chain the <code>group_by()</code> with the <code>summarize()</code> call we used in the previous section:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex    mean_age
  &lt;chr&gt;     &lt;dbl&gt;
1 Female     29.5
2 Male       28.4</code></pre>
</div>
</div>
<p>You get a different summary statistic for each group! The statistics for women are in one row and those for men are in another. (From this output data frame, you can tell that, for example, the mean age for female respondents is 29.5, while that for male respondents is 28.4)</p>
<p>As was mentioned earlier, this kind of grouped summary is the primary reason the <code>summarize()</code> function is so useful!</p>
<hr>
<p>Let’s see another example of a simple <code>group_by()</code> + <code>summarize()</code> operation.</p>
<p>Suppose you were asked to obtain the maximum and minimum weights for individuals in different neighborhoods in the <code>yao</code> data frame. First you would <code>group_by()</code> the <code>neighbourhood</code> variable, then call the <code>max()</code> and <code>min()</code> functions inside <code>summarize()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">max_weight =</span> <span class="fu">max</span>(weight_kg), </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_weight =</span> <span class="fu">min</span>(weight_kg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 3
  neighborhood max_weight min_weight
  &lt;chr&gt;             &lt;dbl&gt;      &lt;dbl&gt;
1 Briqueterie         128         20
2 Carriere            129         14
3 Cité Verte          118         16
4 Ekoudou             135         15
5 Messa                96         19
6 Mokolo              162         16
7 Nkomkana            161         15
8 Tsinga              105         15
9 Tsinga Oliga        100         17</code></pre>
</div>
</div>
<p>Great! With just a few code lines you are able to extract quite a lot of information.</p>
<hr>
<p>Let’s see one more example for good measure. The variable <code>n_days_miss_work</code> tells us the number of days that respondents missed work due to COVID-like symptoms. Individuals who reported no COVID-like symptoms have an <code>NA</code> for this variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(n_days_miss_work)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 971 × 1
   n_days_miss_work
              &lt;dbl&gt;
 1                0
 2               NA
 3               NA
 4                7
 5               NA
 6                7
 7                0
 8                0
 9                0
10               NA
# ℹ 961 more rows</code></pre>
</div>
</div>
<p>To count the total number of work days missed for each sex group, you could try to run the <code>sum()</code> function on the <code>n_days_miss_work</code> variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_days_missed =</span> <span class="fu">sum</span>(n_days_miss_work))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex    total_days_missed
  &lt;chr&gt;              &lt;dbl&gt;
1 Female                NA
2 Male                  NA</code></pre>
</div>
</div>
<p>Hmmm. This gives you <code>NA</code> results because some rows in the <code>n_days_miss_work</code> column have <code>NA</code>s in them, and R cannot find the sum of values containing an <code>NA</code>. To solve this, the argument <code>na.rm = TRUE</code> is needed:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_days_missed =</span> <span class="fu">sum</span>(n_days_miss_work, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex    total_days_missed
  &lt;chr&gt;              &lt;dbl&gt;
1 Female               256
2 Male                 272</code></pre>
</div>
</div>
<p>The output tells us that across all women in the sample, 256 work days were missed due to COVID-like symptoms, and across all men, 272 days.</p>
<hr>
<p>So hopefully now you see why <code>summarize()</code> is so powerful. In combination with <code>group_by()</code>, it lets you obtain highly informative grouped summaries of your datasets with very few lines of code.</p>
<p>Producing such summaries is a very important part of most data analysis workflows, so this skill is likely to come in handy soon!</p>
<div class="callout callout-style-default callout-note callout-titled" title="Vocab">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vocab
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>summarize()</code> produces “Pivot Tables</strong>”</p>
<p>The summary data frames created by <code>summarize()</code> are often called Pivot Tables in the context of spreadsheet software like Microsoft Excel.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>group_by()</code> and <code>summarize()</code> to obtain the mean weight (kg) by smoking status in the <code>yao</code> data frame. Name the average weight column <code>weight_mean</code></p>
<p>The output data frame should look like this:</p>
<table class="table">
<thead>
<tr class="header">
<th>is_smoker</th>
<th>weight_mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ex-smoker</td>
<td></td>
</tr>
<tr class="even">
<td>Non-smoker</td>
<td></td>
</tr>
<tr class="odd">
<td>Smoker</td>
<td></td>
</tr>
<tr class="even">
<td>NA</td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>Q_weight_by_smoking_status <span class="ot">&lt;-</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  ________________________</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  ________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>group_by()</code>, <code>summarize()</code>, and the relevant summary functions to obtain the minimum and maximum heights for each sex in the <code>yao</code> data frame.</p>
<p>Your output should be a data frame with three columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>sex</th>
<th>min_height_cm</th>
<th>max_height_cm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Female</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Male</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>Q_min_max_height_by_sex <span class="ot">&lt;-</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  ________________________</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  ________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>group_by()</code>, <code>summarize()</code>, and the <code>sum()</code> function to calculate the total number of bedridden days (from the <code>n_bedridden_days</code> variable) reported by respondents of each sex.</p>
<p>Your output should be a data frame with two columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>sex</th>
<th>total_bedridden_days</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Female</td>
<td></td>
</tr>
<tr class="even">
<td>Male</td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>Q_sum_bedridden_days <span class="ot">&lt;-</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  ________________________</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  ________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="grouping-by-multiple-variables-nested-grouping" class="level2" data-number="13.7">
<h2 data-number="13.7" class="anchored" data-anchor-id="grouping-by-multiple-variables-nested-grouping"><span class="header-section-number">13.7</span> Grouping by multiple variables (nested grouping)</h2>
<p>It is possible to group a data frame by more than one variable. This is sometimes called “nested” grouping.</p>
<p>Let’s see an example. Suppose you want to know the mean age of men and women <em>in each neighbourhood</em> (rather than the mean age of <em>all</em> women), you could put both <code>sex</code> and <code>neighborhood</code> in the <code>group_by()</code> statement:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 3
# Groups:   sex [2]
   sex    neighborhood mean_age
   &lt;chr&gt;  &lt;chr&gt;           &lt;dbl&gt;
 1 Female Briqueterie      31.6
 2 Female Carriere         28.2
 3 Female Cité Verte       31.8
 4 Female Ekoudou          29.3
 5 Female Messa            30.2
 6 Female Mokolo           28.0
 7 Female Nkomkana         33.0
 8 Female Tsinga           30.6
 9 Female Tsinga Oliga     24.3
10 Male   Briqueterie      33.7
11 Male   Carriere         30.0
12 Male   Cité Verte       27.0
13 Male   Ekoudou          25.2
14 Male   Messa            23.9
15 Male   Mokolo           30.5
16 Male   Nkomkana         29.8
17 Male   Tsinga           28.8
18 Male   Tsinga Oliga     24.3</code></pre>
</div>
</div>
<p>From this output data frame you can tell that, for example, women from Briqueterie have a mean age of 31.6 years, while men from Briqueterie have a mean age of 33.7 years.</p>
<p>The order of the columns listed in <code>group_by()</code> is interchangeable. So if you run <code>group_by(neighborhood, sex)</code> instead of <code>group_by(sex, neighborhood)</code>, you’ll get the same result, although it will be ordered differently:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(neighborhood, sex) <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'neighborhood'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 3
# Groups:   neighborhood [9]
   neighborhood sex    mean_age
   &lt;chr&gt;        &lt;chr&gt;     &lt;dbl&gt;
 1 Briqueterie  Female     31.6
 2 Briqueterie  Male       33.7
 3 Carriere     Female     28.2
 4 Carriere     Male       30.0
 5 Cité Verte   Female     31.8
 6 Cité Verte   Male       27.0
 7 Ekoudou      Female     29.3
 8 Ekoudou      Male       25.2
 9 Messa        Female     30.2
10 Messa        Male       23.9
11 Mokolo       Female     28.0
12 Mokolo       Male       30.5
13 Nkomkana     Female     33.0
14 Nkomkana     Male       29.8
15 Tsinga       Female     30.6
16 Tsinga       Male       28.8
17 Tsinga Oliga Female     24.3
18 Tsinga Oliga Male       24.3</code></pre>
</div>
</div>
<p>Now the column order is different: <code>neighborhood</code> is the first column, and <code>sex</code> is the second. And the row order is also different: rows are first ordered by <code>neighborhood</code>, then ordered by <code>sex</code> within each neighborhood.</p>
<p>But the actual summary statistics are the same. For example, you can again see that women from Briqueterie have a mean age of 31.6 years, while men from Briqueterie have a mean age of 33.7 years.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the <code>yao</code> data frame, group your data by gender (<code>sex</code>) and treatments (<code>treatment_combinations</code>) using <code>group_by</code>. Then, using <code>summarize()</code> and the relevant summary function, calculate the mean weight (<code>weight_kg</code>) for each group.</p>
<p>Your output should be a data frame with three columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>sex</th>
<th>treatment_combinations</th>
<th>mean_weight_kg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>Q_weight_by_sex_treatments <span class="ot">&lt;-</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  ____________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using the <code>yao</code> data frame, group your data by age category (<code>age_category_3</code>), gender (<code>sex</code>), and IgG results (<code>igg_result</code>) using <code>group_by</code>. Then, using <code>summarize()</code> and the relevant summary function, calculate the mean number of bedridden days (<code>n_bedridden_days</code>) for each group.</p>
<p>Your output should be a data frame with four columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>age_category_3</th>
<th>sex</th>
<th>igg_result</th>
<th>mean_n_bedridden_days</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>Q_bedridden_by_age_sex_iggresult <span class="ot">&lt;-</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  ____________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="ungrouping-with-dplyrungroup-why-and-how" class="level2" data-number="13.8">
<h2 data-number="13.8" class="anchored" data-anchor-id="ungrouping-with-dplyrungroup-why-and-how"><span class="header-section-number">13.8</span> Ungrouping with <code>dplyr::ungroup()</code> (why and how)</h2>
<p>When you <code>group_by()</code> more than one variable before using <code>summarize()</code>, the output data frame is still grouped. This persistent grouping can have unwanted downstream effects, so you will sometimes need to use <code>dplyr::ungroup()</code> to ungroup the data before doing further analysis.</p>
<p>To understand <em>why</em> you should <code>ungroup()</code> data, first consider the following example, where we group by only one variable before summarizing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex    mean_age
  &lt;chr&gt;     &lt;dbl&gt;
1 Female     29.5
2 Male       28.4</code></pre>
</div>
</div>
<p>The data comes out like a normal data frame; it is not grouped. You can tell this because there is no information about groups in the header.</p>
<p>But now consider when you group by two variables before summarizing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 3
# Groups:   sex [2]
   sex    neighborhood mean_age
   &lt;chr&gt;  &lt;chr&gt;           &lt;dbl&gt;
 1 Female Briqueterie      31.6
 2 Female Carriere         28.2
 3 Female Cité Verte       31.8
 4 Female Ekoudou          29.3
 5 Female Messa            30.2
 6 Female Mokolo           28.0
 7 Female Nkomkana         33.0
 8 Female Tsinga           30.6
 9 Female Tsinga Oliga     24.3
10 Male   Briqueterie      33.7
11 Male   Carriere         30.0
12 Male   Cité Verte       27.0
13 Male   Ekoudou          25.2
14 Male   Messa            23.9
15 Male   Mokolo           30.5
16 Male   Nkomkana         29.8
17 Male   Tsinga           28.8
18 Male   Tsinga Oliga     24.3</code></pre>
</div>
</div>
<p>Now the header tells you that the data is still grouped by the first variable in <code>group_by()</code>, sex:</p>
<pre><code>  # A tibble: 18 × 3
👉# Groups:   sex [2]👈</code></pre>
<p>What is the implication of this persistent grouping in the data frame? It means that the data frame may exhibit what seems like weird behavior when you try to apply some {dplyr} functions on it.</p>
<p>For example, if you try to <code>select()</code> a single variable, perhaps the <code>mean_age</code> variable, you should normally be able to just use <code>select(mean_age)</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age)) <span class="sc">%&gt;%</span> </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mean_age) <span class="co"># doesn't work as expected </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.
Adding missing grouping variables: `sex`</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 2
# Groups:   sex [2]
   sex    mean_age
   &lt;chr&gt;     &lt;dbl&gt;
 1 Female     31.6
 2 Female     28.2
 3 Female     31.8
 4 Female     29.3
 5 Female     30.2
 6 Female     28.0
 7 Female     33.0
 8 Female     30.6
 9 Female     24.3
10 Male       33.7
11 Male       30.0
12 Male       27.0
13 Male       25.2
14 Male       23.9
15 Male       30.5
16 Male       29.8
17 Male       28.8
18 Male       24.3</code></pre>
</div>
</div>
<p>But as you can see, the grouped-by variable, <code>sex</code>, is <em>still</em> selected, even though we only asked for <code>mean_age</code> in the <code>select()</code> statement.</p>
<p>This is one of the many examples of unique behaviors of grouped data frames. Other dplyr verbs like <code>filter()</code>, <code>mutate()</code> and <code>arrange()</code> also act in special ways on grouped data. We will address this in detail in a future lesson.</p>
<hr>
<p>So you now know <em>why</em> you should ungroup data when you no longer need it grouped. Let’s now see <em>how</em> to ungroup data. It’s quite simple: just add the <code>ungroup()</code> function to your pipe chain. For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age)) <span class="sc">%&gt;%</span> </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 3
   sex    neighborhood mean_age
   &lt;chr&gt;  &lt;chr&gt;           &lt;dbl&gt;
 1 Female Briqueterie      31.6
 2 Female Carriere         28.2
 3 Female Cité Verte       31.8
 4 Female Ekoudou          29.3
 5 Female Messa            30.2
 6 Female Mokolo           28.0
 7 Female Nkomkana         33.0
 8 Female Tsinga           30.6
 9 Female Tsinga Oliga     24.3
10 Male   Briqueterie      33.7
11 Male   Carriere         30.0
12 Male   Cité Verte       27.0
13 Male   Ekoudou          25.2
14 Male   Messa            23.9
15 Male   Mokolo           30.5
16 Male   Nkomkana         29.8
17 Male   Tsinga           28.8
18 Male   Tsinga Oliga     24.3</code></pre>
</div>
</div>
<p>Now that the data frame is ungrouped, it will behave like a normal data frame again. For example, you can <code>select()</code> any column(s) you want; you won’t have some unwanted columns tagging along:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age)) <span class="sc">%&gt;%</span> </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mean_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 1
   mean_age
      &lt;dbl&gt;
 1     31.6
 2     28.2
 3     31.8
 4     29.3
 5     30.2
 6     28.0
 7     33.0
 8     30.6
 9     24.3
10     33.7
11     30.0
12     27.0
13     25.2
14     23.9
15     30.5
16     29.8
17     28.8
18     24.3</code></pre>
</div>
</div>
</section>
<section id="counting-rows" class="level2" data-number="13.9">
<h2 data-number="13.9" class="anchored" data-anchor-id="counting-rows"><span class="header-section-number">13.9</span> Counting rows</h2>
<blockquote class="blockquote">
<p>You can do a lot of data science by just <em>counting</em> and occasionally <em>dividing.</em> - Hadley Wickham, Chief Scientist at RStudio</p>
</blockquote>
<p>A common data summarization task is counting how many observations (rows) there are for each group. You can achieve this with the special <code>n()</code> function from {dplyr}, which is specifically designed to be used within <code>summarise()</code>.</p>
<p>For example, if you want to count how many individuals are in each neighborhood group, you would run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  neighborhood count
  &lt;chr&gt;        &lt;int&gt;
1 Briqueterie    106
2 Carriere       236
3 Cité Verte      72
4 Ekoudou        190
5 Messa           48
6 Mokolo          96
7 Nkomkana        75
8 Tsinga          81
9 Tsinga Oliga    67</code></pre>
</div>
</div>
<p>As you can see, the <code>n()</code> function does not require any arguments. It just “knows its job” in the data frame!</p>
<hr>
<p>Of course, you can include other summary statistics in the same <code>summarize()</code> call. For example, below we also calculate the mean age per neighborhood.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>(), </span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_age =</span> <span class="fu">mean</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 3
  neighborhood count mean_age
  &lt;chr&gt;        &lt;int&gt;    &lt;dbl&gt;
1 Briqueterie    106     32.5
2 Carriere       236     28.9
3 Cité Verte      72     29.9
4 Ekoudou        190     27.6
5 Messa           48     27.3
6 Mokolo          96     29.1
7 Nkomkana        75     31.7
8 Tsinga          81     29.7
9 Tsinga Oliga    67     24.3</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Group your <code>yao</code> data frame by the respondents’ occupation (<code>occupation</code>) and use <code>summarize()</code> to create columns that show:</p>
<ul>
<li>how many individuals there are with each occupation (think of the <code>n()</code> function)</li>
<li>the mean number of work days missed (<code>n_days_miss_work</code>) by those in that occupation</li>
</ul>
<p>Your output should be a data frame with three columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>occupation</th>
<th>count</th>
<th>mean_n_days_miss_work</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>Q_occupation_summary <span class="ot">&lt;-</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  ____________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="counting-rows-that-meet-a-condition" class="level3" data-number="13.9.1">
<h3 data-number="13.9.1" class="anchored" data-anchor-id="counting-rows-that-meet-a-condition"><span class="header-section-number">13.9.1</span> Counting rows that meet a condition</h3>
<p>Rather than counting <em>all</em> rows as above, it is sometimes more useful to count just the rows that meet specific conditions. This can be done easily by placing the required conditions within the <code>sum()</code> function.</p>
<p>For example, to count the number of people under 18 in each neighborhood, you place the condition <code>age &lt; 18</code> inside <code>sum()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count_under_18 =</span> <span class="fu">sum</span>(age <span class="sc">&lt;</span> <span class="dv">18</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  neighborhood count_under_18
  &lt;chr&gt;                 &lt;int&gt;
1 Briqueterie              28
2 Carriere                 58
3 Cité Verte               19
4 Ekoudou                  66
5 Messa                    18
6 Mokolo                   32
7 Nkomkana                 22
8 Tsinga                   23
9 Tsinga Oliga             25</code></pre>
</div>
</div>
<hr>
<p>Similarly, to count the number of people with doctorate degrees in each neighborhood, you place the condition <code>highest_education == "Doctorate"</code> inside <code>sum()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count_with_doctorates =</span> <span class="fu">sum</span>(highest_education <span class="sc">==</span> <span class="st">"Doctorate"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  neighborhood count_with_doctorates
  &lt;chr&gt;                        &lt;int&gt;
1 Briqueterie                      2
2 Carriere                         1
3 Cité Verte                       1
4 Ekoudou                          1
5 Messa                            2
6 Mokolo                           0
7 Nkomkana                         4
8 Tsinga                           3
9 Tsinga Oliga                     3</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Challenge">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Challenge
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Under the hood: counting with conditions</strong></p>
<p>Why are you able to use <code>sum()</code> which is meant to add numbers, on a condition like <code>highest_education == "Doctorate"</code>?</p>
<p>Using <code>sum()</code> on a condition works because the condition evaluates to the Boolean values <code>TRUE</code> and <code>FALSE</code>. And these Boolean values are treated as numbers (where <code>TRUE</code> equals 1 and <code>FALSE</code> equals 0), and numbers can, of course, be summed.</p>
<p>The code below demonstrates what is going on under the hood in a step-by-step way. Run through it and see if you can follow.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>demo_of_condition_sums <span class="ot">&lt;-</span> yao <span class="sc">%&gt;%</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(highest_education) <span class="sc">%&gt;%</span> </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">with_doctorate =</span> highest_education <span class="sc">==</span> <span class="st">"Doctorate"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">numeric_with_doctorate =</span> <span class="fu">as.numeric</span>(with_doctorate))</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>demo_of_condition_sums</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 971 × 3
   highest_education with_doctorate numeric_with_doctorate
   &lt;chr&gt;             &lt;lgl&gt;                           &lt;dbl&gt;
 1 Secondary         FALSE                               0
 2 University        FALSE                               0
 3 University        FALSE                               0
 4 Secondary         FALSE                               0
 5 Primary           FALSE                               0
 6 Secondary         FALSE                               0
 7 Secondary         FALSE                               0
 8 Doctorate         TRUE                                1
 9 Secondary         FALSE                               0
10 Secondary         FALSE                               0
# ℹ 961 more rows</code></pre>
</div>
</div>
<p>The numeric values can then be added to produce a count of rows fulfilling the condition <code>highest_education == "Doctorate"</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>demo_of_condition_sums <span class="sc">%&gt;%</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count_with_doctorate =</span> <span class="fu">sum</span>(numeric_with_doctorate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  count_with_doctorate
                 &lt;dbl&gt;
1                   17</code></pre>
</div>
</div>
</div>
</div>
<hr>
<p>For a final illustration of counting with conditions, consider the <code>treatment_combinations</code> variable, which lists the treatments received by people with COVID-like symptoms. People who received no treatments have an <code>NA</code> value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(treatment_combinations)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 971 × 1
   treatment_combinations        
   &lt;chr&gt;                         
 1 Paracetamol                   
 2 &lt;NA&gt;                          
 3 &lt;NA&gt;                          
 4 Antibiotics                   
 5 &lt;NA&gt;                          
 6 Paracetamol--Antibiotics      
 7 Traditional meds.             
 8 Paracetamol                   
 9 Paracetamol--Traditional meds.
10 &lt;NA&gt;                          
# ℹ 961 more rows</code></pre>
</div>
</div>
<p>If you want to count the number of people who received <em>no treatment</em>, you would sum up those who meet the <code>is.na(treatment_combinations)</code> condition:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">unknown_treatments =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(treatment_combinations)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  neighborhood unknown_treatments
  &lt;chr&gt;                     &lt;int&gt;
1 Briqueterie                  82
2 Carriere                    192
3 Cité Verte                   46
4 Ekoudou                     133
5 Messa                        35
6 Mokolo                       65
7 Nkomkana                     53
8 Tsinga                       56
9 Tsinga Oliga                 47</code></pre>
</div>
</div>
<p>These are the people with <code>NA</code> values for the <code>treatment_combinations</code> column.</p>
<p>To count the people who <em>did</em> receive some treatment, you can simply negate the <code>is.na()</code> function with <code>!</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">known_treatments =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(treatment_combinations)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  neighborhood known_treatments
  &lt;chr&gt;                   &lt;int&gt;
1 Briqueterie                24
2 Carriere                   44
3 Cité Verte                 26
4 Ekoudou                    57
5 Messa                      13
6 Mokolo                     31
7 Nkomkana                   22
8 Tsinga                     25
9 Tsinga Oliga               20</code></pre>
</div>
</div>
<p>PLEASE SKIP THE PRACTICE QUESTION ON CHECKING SYMPTOMS FOR ADULTS. WE DECIDED TO REMOVE IT.</p>
</section>
<section id="dplyrcount" class="level3" data-number="13.9.2">
<h3 data-number="13.9.2" class="anchored" data-anchor-id="dplyrcount"><span class="header-section-number">13.9.2</span> dplyr::count()</h3>
<p>The <code>dplyr::count()</code> function wraps a bunch of things into one beautiful friendly line of code to help you find counts of observations by group.</p>
<p>Let’s use <code>dplyr::count()</code> on our <code>occupation</code> variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(occupation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 28 × 2
   occupation                              n
   &lt;chr&gt;                               &lt;int&gt;
 1 Farmer                                  5
 2 Farmer--Other                           1
 3 Home-maker                             65
 4 Home-maker--Farmer                      2
 5 Home-maker--Informal worker             3
 6 Home-maker--Informal worker--Farmer     1
 7 Home-maker--Trader                      3
 8 Informal worker                       189
 9 Informal worker--Other                  2
10 Informal worker--Trader                 4
# ℹ 18 more rows</code></pre>
</div>
</div>
<p>Note that this is the same output as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(occupation) <span class="sc">%&gt;%</span> </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 28 × 2
   occupation                              n
   &lt;chr&gt;                               &lt;int&gt;
 1 Farmer                                  5
 2 Farmer--Other                           1
 3 Home-maker                             65
 4 Home-maker--Farmer                      2
 5 Home-maker--Informal worker             3
 6 Home-maker--Informal worker--Farmer     1
 7 Home-maker--Trader                      3
 8 Informal worker                       189
 9 Informal worker--Other                  2
10 Informal worker--Trader                 4
# ℹ 18 more rows</code></pre>
</div>
</div>
<p>You can also apply <code>dplyr::count()</code> in a nested fashion:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sex, occupation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 3
   sex    occupation                              n
   &lt;chr&gt;  &lt;chr&gt;                               &lt;int&gt;
 1 Female Farmer                                  3
 2 Female Home-maker                             65
 3 Female Home-maker--Farmer                      2
 4 Female Home-maker--Informal worker             3
 5 Female Home-maker--Informal worker--Farmer     1
 6 Female Home-maker--Trader                      3
 7 Female Informal worker                        77
 8 Female Informal worker--Trader                 1
 9 Female No response                             8
10 Female Other                                   6
# ℹ 30 more rows</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>count()</code> verb gives you key information about your dataset in a very quick manner. Let’s look at our IgG results stratified by age category and sex in one line of code.</p>
<p>Using the <code>yao</code> data frame, count the different combinations of gender (<code>sex</code>), age categories (<code>age_category_3</code>) and IgG results (<code>igg_result</code>).</p>
<p>Your output should be a data frame with four columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>sex</th>
<th>age_category_3</th>
<th>igg_result</th>
<th>n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>Q_count_iggresults_stratified_by_sex_agecategories <span class="ot">&lt;-</span> </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  ____________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using the <code>yao</code> data frame, count the different combinations of age categories (<code>age_category_3</code>) and number of bedridden days (<code>n_bedridden_days</code>).</p>
<p>Your output should be a data frame with three columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>age_category_3</th>
<th>n_bedridden_days</th>
<th>n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>Q_count_bedridden_age_categories <span class="ot">&lt;-</span> </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  ____________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<hr>
<p>The downside of <code>count()</code> is that it can only give you a single summary statistic in the data frame. When you use <code>summarize()</code> and <code>n()</code> you can include multiple summary statistics. For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>(), </span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_age =</span> <span class="fu">median</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 4
# Groups:   sex [2]
   sex    neighborhood count median_age
   &lt;chr&gt;  &lt;chr&gt;        &lt;int&gt;      &lt;dbl&gt;
 1 Female Briqueterie     61       28  
 2 Female Carriere       140       25.5
 3 Female Cité Verte      44       28  
 4 Female Ekoudou        110       26.5
 5 Female Messa           26       27.5
 6 Female Mokolo          53       23  
 7 Female Nkomkana        43       28  
 8 Female Tsinga          42       29  
 9 Female Tsinga Oliga    30       23.5
10 Male   Briqueterie     45       28  
11 Male   Carriere        96       27  
12 Male   Cité Verte      28       22.5
13 Male   Ekoudou         80       21.5
14 Male   Messa           22       24.5
15 Male   Mokolo          43       32  
16 Male   Nkomkana        32       27  
17 Male   Tsinga          39       27  
18 Male   Tsinga Oliga    37       21  </code></pre>
</div>
</div>
<p>But <code>count()</code> can only yield counts:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, neighborhood) <span class="sc">%&gt;%</span> </span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 3
# Groups:   sex, neighborhood [18]
   sex    neighborhood     n
   &lt;chr&gt;  &lt;chr&gt;        &lt;int&gt;
 1 Female Briqueterie     61
 2 Female Carriere       140
 3 Female Cité Verte      44
 4 Female Ekoudou        110
 5 Female Messa           26
 6 Female Mokolo          53
 7 Female Nkomkana        43
 8 Female Tsinga          42
 9 Female Tsinga Oliga    30
10 Male   Briqueterie     45
11 Male   Carriere        96
12 Male   Cité Verte      28
13 Male   Ekoudou         80
14 Male   Messa           22
15 Male   Mokolo          43
16 Male   Nkomkana        32
17 Male   Tsinga          39
18 Male   Tsinga Oliga    37</code></pre>
</div>
</div>
</section>
</section>
<section id="including-missing-combinations-in-summaries" class="level2" data-number="13.10">
<h2 data-number="13.10" class="anchored" data-anchor-id="including-missing-combinations-in-summaries"><span class="header-section-number">13.10</span> Including missing combinations in summaries</h2>
<p>When you use <code>group_by()</code> and <code>summarize()</code> on multiple variables, you obtain a summary statistic for every unique combination of the grouped variables. For instance, consider the code and output below, which counts the number of individuals in each age-sex group:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, age_category_3) <span class="sc">%&gt;%</span> </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_individuals =</span> <span class="fu">n</span>()) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   sex [2]
  sex    age_category_3 number_of_individuals
  &lt;chr&gt;  &lt;chr&gt;                          &lt;int&gt;
1 Female Adult                            368
2 Female Child                            155
3 Female Senior                            26
4 Male   Adult                            267
5 Male   Child                            136
6 Male   Senior                            19</code></pre>
</div>
</div>
<p>In the output data frame, there is one row for each combination of sex and age group (Female—Adult, Female—Child and so on).</p>
<p>But what happens if one of these combinations is not present in the data?</p>
<p>Let’s create an artificial example to observe this. With the code below, we artificially drop all male children from the <code>yao</code> data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>yao_no_male_children <span class="ot">&lt;-</span> </span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span> </span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(sex <span class="sc">==</span> <span class="st">"Male"</span> <span class="sc">&amp;</span> age_category_3 <span class="sc">==</span> <span class="st">"Child"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now if you run the same <code>group_by()</code> and <code>summarize()</code> call on <code>yao_no_male_children</code>, you’ll notice the missing combination:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>yao_no_male_children <span class="sc">%&gt;%</span> </span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, age_category_3) <span class="sc">%&gt;%</span> </span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_individuals =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
# Groups:   sex [2]
  sex    age_category_3 number_of_individuals
  &lt;chr&gt;  &lt;chr&gt;                          &lt;int&gt;
1 Female Adult                            368
2 Female Child                            155
3 Female Senior                            26
4 Male   Adult                            267
5 Male   Senior                            19</code></pre>
</div>
</div>
<p>Indeed, there is no row for male children.</p>
<p>But sometimes it is useful to include such missing combinations in the output data frame, with an <code>NA</code> or 0 value for the summary statistic.</p>
<p>To do this, you can run the following code instead:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>yao_no_male_children <span class="sc">%&gt;%</span> </span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert variables to factors</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as.factor</span>(sex), </span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">age_category_3 =</span> <span class="fu">as.factor</span>(age_category_3)) <span class="sc">%&gt;%</span> </span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Note the the .drop = FALSE argument</span></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, age_category_3, <span class="at">.drop =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_individuals =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   sex [2]
  sex    age_category_3 number_of_individuals
  &lt;fct&gt;  &lt;fct&gt;                          &lt;int&gt;
1 Female Adult                            368
2 Female Child                            155
3 Female Senior                            26
4 Male   Adult                            267
5 Male   Child                              0
6 Male   Senior                            19</code></pre>
</div>
</div>
<p>What does the code do?</p>
<ul>
<li><p>First it converts the grouping variables to factors with <code>as.factor()</code> (inside a <code>mutate()</code> call)</p></li>
<li><p>Then it uses the argument <code>.drop = FALSE</code> in the <code>group_by()</code> function to avoid dropping the missing combinations.</p></li>
</ul>
<p>Now you have a clear <code>0</code> count for the number of male children!</p>
<hr>
<p>Let’s see one more example, this time without artificially modifying our data.</p>
<p>The code below calculates the average age by sex and education group:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, highest_education) <span class="sc">%&gt;%</span> </span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 3
# Groups:   sex [2]
   sex    highest_education     mean_age
   &lt;chr&gt;  &lt;chr&gt;                    &lt;dbl&gt;
 1 Female Doctorate                 28  
 2 Female No formal instruction     45.6
 3 Female No response               35  
 4 Female Primary                   26.8
 5 Female Secondary                 28.8
 6 Female University                31.5
 7 Male   Doctorate                 42.2
 8 Male   No formal instruction     37.9
 9 Male   No response               22  
10 Male   Other                      5.5
11 Male   Primary                   22.9
12 Male   Secondary                 29.4
13 Male   University                31.9</code></pre>
</div>
</div>
<p>Notice that in the output data frame, there are 7 rows for men but only 6 rows for women, because no woman answered “Other” to the question on highest education level.</p>
<p>If you nonetheless want to include the “Female—Other” row in the output data frame, you would run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>yao <span class="sc">%&gt;%</span> </span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as.factor</span>(sex), </span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">highest_education =</span> <span class="fu">as.factor</span>(highest_education)) <span class="sc">%&gt;%</span> </span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, highest_education, <span class="at">.drop =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_age =</span> <span class="fu">mean</span>(age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 3
# Groups:   sex [2]
   sex    highest_education     mean_age
   &lt;fct&gt;  &lt;fct&gt;                    &lt;dbl&gt;
 1 Female Doctorate                 28  
 2 Female No formal instruction     45.6
 3 Female No response               35  
 4 Female Other                    NaN  
 5 Female Primary                   26.8
 6 Female Secondary                 28.8
 7 Female University                31.5
 8 Male   Doctorate                 42.2
 9 Male   No formal instruction     37.9
10 Male   No response               22  
11 Male   Other                      5.5
12 Male   Primary                   22.9
13 Male   Secondary                 29.4
14 Male   University                31.9</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Practice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the <code>yao</code> data frame, let’s calculate the median age when grouping by neighborhood, age_category, and gender</p>
<p>Note, we want all possible combinations of these three variables (not just those present in our data).</p>
<p>Pay attention to two data wrangling imperatives!</p>
<ul>
<li>convert your grouping variables to factors beforehand using <code>mutate()</code></li>
<li>calculate your statistic, the median, while removing any <code>NA</code> values.</li>
</ul>
<p>Your output should be a data frame with four columns named as shown below:</p>
<table class="table">
<thead>
<tr class="header">
<th>neighborhood</th>
<th>age_category_3</th>
<th>sex</th>
<th>median_age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>Q_median_age_by_neighborhood_agecategory_sex <span class="ot">&lt;-</span> </span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>  yao <span class="sc">%&gt;%</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>  ____________________________</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Side Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Side Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Why include missing combinations?</strong></p>
<p>Above, we mentioned that including missing combinations is often useful in the data analysis workflow. Let’s see one use case: plotting with {ggplot}. If you have not yet learned {ggplot}, that is okay, just focus on the plot outputs.</p>
<p>To make a dodged bar chart with the age-sex counts of <code>yao_no_male_children</code>, you could run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>yao_no_male_children <span class="sc">%&gt;%</span> </span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, age_category_3) <span class="sc">%&gt;%</span> </span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_individuals =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># pass the output to ggplot</span></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> number_of_individuals, <span class="at">fill =</span> age_category_3), </span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">position =</span> <span class="st">"dodge"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="untangled_ls05_groupby_summarize_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Not very elegant! Ideally there should be an empty space indicating 0 for the number of male children.</p>
<p>If you instead implement the procedure to include missing combinations, you get a more natural dodged bar plot, with an empty space for male children:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>yao_no_male_children <span class="sc">%&gt;%</span> </span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as.factor</span>(sex), </span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">age_category_3 =</span> <span class="fu">as.factor</span>(age_category_3)) <span class="sc">%&gt;%</span> </span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, age_category_3, <span class="at">.drop =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_individuals =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># pass the output to ggplot</span></span>
<span id="cb103-9"><a href="#cb103-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb103-10"><a href="#cb103-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> number_of_individuals, <span class="at">fill =</span> age_category_3), </span>
<span id="cb103-11"><a href="#cb103-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">position =</span> <span class="st">"dodge"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="untangled_ls05_groupby_summarize_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Much better!</p>
<p>By the way, this output can be improved slightly by setting the factor levels for age to their proper ascending order: first “Child”, then “Adult” then “Senior”:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>yao_no_male_children <span class="sc">%&gt;%</span> </span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">as.factor</span>(sex), </span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">age_category_3 =</span> <span class="fu">factor</span>(age_category_3, </span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Child"</span>, </span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>                                            <span class="st">"Adult"</span>, </span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>                                            <span class="st">"Senior"</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex, age_category_3, <span class="at">.drop =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">number_of_individuals =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb105-10"><a href="#cb105-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb105-11"><a href="#cb105-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># pass the output to ggplot</span></span>
<span id="cb105-12"><a href="#cb105-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb105-13"><a href="#cb105-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> number_of_individuals, <span class="at">fill =</span> age_category_3), </span>
<span id="cb105-14"><a href="#cb105-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">position =</span> <span class="st">"dodge"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="untangled_ls05_groupby_summarize_files/figure-html/unnamed-chunk-64-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</section>
<section id="wrap-up" class="level2" data-number="13.11">
<h2 data-number="13.11" class="anchored" data-anchor-id="wrap-up"><span class="header-section-number">13.11</span> Wrap up</h2>
<p>You have now seen how to obtain quick summary statistics from your data, either for exploratory data or for further data presentation or plotting.</p>
<p>Additionally, you have discovered one of the marvels of {dplyr}, the possibility to group your data using <code>group_by()</code>.</p>
<p><code>group_by()</code> combined with <code>summarize()</code> is a one of the most common grouping manipulations.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/custom_dplyr_groupby_summarize.png" class="img-fluid figure-img" width="400"></p>
<figcaption class="figure-caption">Fig: summarize() and its use combined with group_by().</figcaption>
</figure>
</div>
<p>However, you can also combine <code>group_by()</code> with many of the other {dplyr} verbs: this is what we will cover in our next lesson. See you soon !</p>
<p></p><div class="user-profile-details"><ul><li><img src="./Users/kendavidn/Dropbox/tgc_github_projects/idar_book/global/contributors/lolovanco.jpg" width="50px" height="50px"> <name><a href="https://thegraphcourses.org/members/lolovanco" target="_blank">LAURE VANCAUWENBERGHE </a> </name> <br> <label>Data analyst, the GRAPH Network</label> <p>A firm believer in science for good, striving to ally programming, health and education</p></li></ul></div> <div class="user-profile-details"><ul><li><img src="./Users/kendavidn/Dropbox/tgc_github_projects/idar_book/global/contributors/avallecam.jpg" width="50px" height="50px"> <name><a href="https://thegraphcourses.org/members/avallecam/" target="_blank">ANDREE VALLE CAMPOS </a> </name> <br> <label>R Developer and Instructor, the GRAPH Network</label> <p>Motivated by reproducible science and education</p></li></ul></div> <div class="user-profile-details"><ul><li><img src="./Users/kendavidn/Dropbox/tgc_github_projects/idar_book/global/contributors/kendavidn.jpg" width="50px" height="50px"> <name><a href="https://thegraphcourses.org/members/kendavidn/" target="_blank">KENE DAVID NWOSU </a> </name> <br> <label>Data analyst, the GRAPH Network</label> <p>Passionate about world improvement</p></li></ul></div><p></p>
<p>Thank you to <a href="https://thegraphcourses.org/members/alice" target="_blank">Alice Osmaston</a> and <a href="https://thegraphcourses.org/members/saif" target="_blank">Saifeldin Shehata</a> for their comments and review.</p>
</section>
<section id="references" class="level2 unlisted unnumbered">
<h2 class="unlisted unnumbered anchored" data-anchor-id="references">References</h2>
<p>Some material in this lesson was adapted from the following sources:</p>
<ul>
<li><p>Horst, A. (2022). <em>Dplyr-learnr</em>. <a href="https://github.com/allisonhorst/dplyr-learnr" class="uri">https://github.com/allisonhorst/dplyr-learnr</a> (Original work published 2020)</p></li>
<li><p><em>Group by one or more variables</em>. (n.d.). Retrieved 21 February 2022, from <a href="https://dplyr.tidyverse.org/reference/group_by.html" class="uri">https://dplyr.tidyverse.org/reference/group_by.html</a></p></li>
<li><p><em>Summarise each group to fewer rows</em>. (n.d.). Retrieved 21 February 2022, from <a href="https://dplyr.tidyverse.org/reference/summarize.html" class="uri">https://dplyr.tidyverse.org/reference/summarize.html</a></p></li>
<li><p>The Carpentries. (n.d.). <em>Grouped operations using `dplyr`</em>. Grouped operations using `dplyr` – Introduction to R/tidyverse for Exploratory Data Analysis. Retrieved July 28, 2022, from <a href="https://tavareshugo.github.io/r-intro-tidyverse-gapminder/06-grouped_operations_dplyr/index.html" class="uri">https://tavareshugo.github.io/r-intro-tidyverse-gapminder/06-grouped_operations_dplyr/index.html</a></p></li>
</ul>
<p>Artwork was adapted from:</p>
<ul>
<li>Horst, A. (2022). <em>R &amp; stats illustrations by Allison Horst</em>. <a href="https://github.com/allisonhorst/stats-illustrations" class="uri">https://github.com/allisonhorst/stats-illustrations</a> (Original work published 2018)</li>
</ul>
</section>
<section id="solutions" class="level2" data-number="13.12">
<h2 data-number="13.12" class="anchored" data-anchor-id="solutions"><span class="header-section-number">13.12</span> Solutions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_weight_summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_weight_summary &lt;- 
  yao %&gt;%
      summarize(mean_weight_kg = mean(weight_kg),
                median_weight_kg = median(weight_kg),
                sd_weight_kg = sd(weight_kg))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_height_summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_height_summary &lt;- 
  yao %&gt;%
      summarize(min_height_cm = min(height_cm),
                max_height_cm = max(height_cm))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_weight_by_smoking_status</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_weight_by_smoking_status &lt;- 
  yao %&gt;% 
  group_by(is_smoker) %&gt;% 
  summarise(weight_mean = mean(weight_kg))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_min_max_height_by_sex</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_min_max_height_by_sex &lt;- 
  yao %&gt;% 
  group_by(sex) %&gt;%
  summarise(min_height_cm = min(height_cm),
            max_height_cm = max(height_cm))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_sum_bedridden_days</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_sum_bedridden_days &lt;- 
  yao %&gt;% 
  group_by(sex) %&gt;% 
  summarise(total_bedridden_days = sum(n_bedridden_days, na.rm = T))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_weight_by_sex_treatments</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

  
Q_weight_by_sex_treatments &lt;- 
  yao %&gt;% 
  group_by(sex, treatment_combinations) %&gt;%
  summarise(mean_weight_kg = mean(weight_kg, na.rm = T))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_bedridden_by_age_sex_iggresult</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_bedridden_by_age_sex_iggresult &lt;- 
  yao %&gt;% 
  group_by(age_category_3, sex, igg_result) %&gt;% 
  summarise(mean_n_bedridden_days = mean(n_bedridden_days, na.rm = T))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_occupation_summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_occupation_summary &lt;- 
  yao %&gt;% 
  group_by(occupation) %&gt;%
  summarise(count = n(),
            mean_n_days_miss_work = mean(n_days_miss_work, na.rm=TRUE))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_count_iggresults_stratified_by_sex_agecategories</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_count_iggresults_stratified_by_sex_agecategories &lt;- 
  yao %&gt;% 
  count(sex, age_category_3, igg_result)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_count_bedridden_age_categories</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_count_bedridden_age_categories &lt;- 
  yao %&gt;% 
  count(age_category_3, n_bedridden_days)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r tgc-code-block code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.SOLUTION_Q_median_age_by_neighborhood_agecategory_sex</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Q_median_age_by_neighborhood_agecategory_sex &lt;- 
  yao %&gt;% 
  mutate(neighborhood = as.factor(neighborhood),
             age_category_3 = as.factor(age_category_3),
             sex = as.factor(sex)) %&gt;%
  group_by(neighborhood, age_category_3, sex, .drop=FALSE) %&gt;%
  summarize(median_age = median(age, na.rm=TRUE))</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./untangled_ls04_conditional_mutate.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Conditional mutating</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./untangled_ls06_group_by_other_verbs.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Grouped filter, mutate and arrange</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Book created by <a href="https://thegraphcourses.org/">The GRAPH Courses</a></div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">For a PDF copy, please visit this <a href="https://raw.githubusercontent.com/the-graph-courses/idar_book/main/pdf/Introduction-to-Data-Analysis-with-R.pdf">page</a>.</div>
  </div>
</footer>



</body></html>